### ISSUE TITLE
[Issue]: WG fails to inspect postgres database

### ISSUE THREAD

**Issue by AesSedai** [wundergraph/wundergraph#1104] opened 2023-07-04 20:23 UTC
### Description

I was following up on my [other issue](https://github.com/wundergraph/wundergraph/issues/1020) and found that I still can't add my demo postgres data source, albeit with a new error this time:
```
20:18:52 PM ERROR: database introspection failed: Error: Command failed with exit code 1: /app/node_modules/@wundergraph/wunderctl/download/wunderctl introspect postgresql postgres://admin:admin@db:5432/db?schema=public --outfile=generated/introspection/database/edc0979a1bd56f32846f3aeec2d9487f3f71db78.json --debug --wundergraph-dir /app/.wundergraph --cli-log-level info --pretty-logging=true
Error: EOF
{"level":"debug","time":1688501932704,"caller":"commands/root.go:97","msg":"starting without env file","hostname":"551db384d694","pid":242,"component":"@wundergraph/wunderctl"} {"component":"@wundergraph/sdk"}
20:18:52 PM INFO: retrying database introspection 5/5 {"component":"@wundergraph/sdk"}
20:18:52 PM FATAL: introspection of postgresql database failed after 5 attempts, make sure it's accessible at: postgres://admin:admin@db:5432/db?schema=public
    Did you forget to add tables to the database? Make sure, you've run your initial migration.
    The introspection fails if there are no tables.
    Are you using a custom database schema? Make sure it's selected in the database URL.
    Please restart "wunderctl up" once the DB is running.
     {"component":"@wundergraph/sdk"}
```

### Reproduction

Using `"@wundergraph/sdk": "^0.166.1"`

Same reproduction still available at https://github.com/AesSedai/wundergraph-stringify-example

When trying to bring up the services with `docker compose up` the wundergraph introspection service still fails.

**Comment by Aenimus** [comment] 2023-07-04 23:55
Can you confirm the endpoint works and that the DB has been seeded?

**Comment by AesSedai** [comment] 2023-07-05 01:53
@Aenimus Yes, the database endpoint works via `psql` and the DB has been seeded.

Here's some terminal output, `docker compose up` is on the left and `docker ps` + `psql` on the right. I can connect to the db with other containers too in another project I have, but WG fails to inspect still.
![image](https://github.com/wundergraph/wundergraph/assets/7980540/325e2d90-99ac-43a4-9395-9a960885098e)

**Comment by HXavS** [comment] 2023-07-05 19:12
Also having issues with Postgres hosted on NeonDB. Error is cloud deploy look the same. Local generate works fine
https://discord.com/channels/738739428314316823/1125211433500672001

**Comment by abdelhameedhamdy** [comment] 2023-07-09 17:11
Got the same issue on wg cloud after 166.1 with neon Postgres db connection
Local development is introspecting with no issue.

**Comment by Aenimus** [comment] 2023-07-10 08:42
Thank you all, we're investigating this. 

@AesSedai @abdelhameedhamdy does downgrading to 0.166.0 allows a successful build? The break is specifically 166.1?

**Comment by fiam** [comment] 2023-07-10 12:23
@AesSedai @HXavS @abdelhameedhamdy I've noticed that `main` doesn't download the right binaries for linux/arm64 (it downloads linux/amd64). Are you, by any chance, seeing these errors when running linux/arm64 containers?

**Comment by fiam** [comment] 2023-07-13 13:22
Hello @abdelhameedhamdy - Thanks for the confirmation! It seems to be a separate issue, we'll look into it.

**Comment by austinm911** [comment] 2023-07-15 18:33
@fiam same problem using `0.169.0`
Deployment ID: 9da006ad-be56-4046-8df8-3490bd05b95a

![image](https://github.com/wundergraph/wundergraph/assets/31991302/b7d0635b-92fa-4a7f-9633-74e538a93c33)

**Comment by HXavS** [comment] 2023-07-17 16:36
@fiam My issue is with wundergraph cloud

**Comment by fiam** [comment] 2023-07-18 10:52
@HXavS @abdelhameedhamdy @austinm911 Thanks for the additional information. We've managed to reproduce this and a fix is now in place. It will be included in the next release.

**Closed** 2023-07-18 11:10 UTC
Labels: bug
