### ISSUE TITLE
[Issue]: WG (openApiV2): Operation "CreateUser" throws "gateway timeout" error

### ISSUE THREAD

**Issue by Xymmer** [wundergraph/wundergraph#1197] opened 2023-08-16 20:02 UTC
### Description

Operation "CreateUser" 
- throws "gateway timeout" error; even the "requestTimeoutSecond" is set to 30.
- throws error 
`{"code":"ResponseError","message":"hooks pipeline failed: ResolveGraphQLResponse failed: Value is array, but can't find closing ']' symbol\n"}`

(two different bug reports on our side)

### Reproduction

Try CreateUser.
@wundergraph/sdk: 0.174.0

**Comment by WeizhengSap** [comment] 2023-09-29 14:11
the request payload is:
```
{"baseSiteId":"electronics-spa","postBaseSiteIdUsersInput":{"firstName":"test","lastName":"test","password":"!QAZ2wsx","titleCode":"mr","uid":"test@test.com"}}
```

The error is "500 (Internal Server Error)", and come from the fetch function in "client":
```
async fetch(input, init = {}) {
       ...
        try {
            const resp = await fetchImpl(input, {
                credentials: 'include',
                mode: 'cors',
                ...init,
            });
            return resp;
        }
        ...
    }
```

**Comment by Pagebakers** [comment] 2023-10-03 12:49
Could you provide the UserSignUp and User schema's please so we can try reproduce this.

**Comment by Pagebakers** [comment] 2023-10-06 09:47
@Xymmer this seems to be related to #1200 because it receives XML which cannot be parsed. We are waiting for our fix to be released by the upstream.

**Comment by WeizhengSap** [comment] 2023-10-17 13:03
@Pagebakers : even I used workaround, this `CreateUser` give us gateway timeout error.

**Comment by Pagebakers** [comment] 2023-10-20 09:54
Can you try the following please?

In the `createUser` endpoint in the schema move `application/json` to the first key. (just to make sure this is not the cause)
```
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserSignUp'
          application/xml:
            schema:
              $ref: '#/components/schemas/UserSignUp'
```

And then run `wunderctl up --debug`  and run the operation. Please share the full log out put (in Slack)

**Comment by Pagebakers** [comment] 2023-10-26 13:31
This has been fixed in the latest release.

**Closed by Pagebakers** 2023-10-26 13:31 UTC
